### ISSUE TITLE
[Bug]: electron版本无法升级到v14及以上

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#1272]
### 版本信息

```sh
+-- @modern-js/app-tools@1.6.9
`-- @modern-js/plugin-electron@1.0.19
  `-- @modern-js/app-tools@1.6.9 deduped
```

### 问题详情

目前modernjs只支持electron@13(对应nodejs为14.17.0)。项目需要使用electron的更高版本以使用electron和node的新特性，且有些依赖也需要更高版本的nodejs，因此需要将electron升级到更高的版本。但是将electron升级到>=14之后，会报如下错误：

```
App threw an error during load
Error: @electron/remote >= 2.x is required for Electron >= 14. See https://github.com/electron/remote/blob/main/docs/migration-2.md for migration instructions.
    at initialize (D:\proj\learn-modern\node_modules\@electron\remote\dist\src\main\server.js:342:15)
    at ElectronRuntime.initEnvironment (D:\proj\learn-modern\node_modules\@modern-js\electron-runtime\dist\js\node\main.js:85:26)
    at ElectronRuntime.initEnvs (D:\proj\learn-modern\node_modules\@modern-js\electron-runtime\dist\js\node\main.js:71:10)
    at new ElectronRuntime (D:\proj\learn-modern\node_modules\@modern-js\electron-runtime\dist\js\node\main.js:58:10)
    at Object.<anonymous> (D:\proj\learn-modern\src-electron\/main.ts:25:17)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Module._compile (D:\proj\learn-modern\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Object.newLoader [as .ts] (D:\proj\learn-modern\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

主要原因好像是@modern-js\electron-runtime的要求 electron 的版本 < 14.0.0， 为什么有这个要求呢？

### 复现链接

无

### 复现步骤

无

**Comment by chenjiahan** [comment]
由于 Modern.js 整体规划调整，从 Modern.js 2.0 版本开始，将不再提供 Electron 工程方案，且 Modern.js v1 的 Electron 工程方案也不再进行新的迭代。

因此，Electron 相关 issue 将被关闭。如果有相关需求，欢迎 fork Modern.js Electron 相关代码进行二次开发，感谢理解~
