### ISSUE TITLE
[Bug]: output.polyfill = ‘ua'时，配置文件修改触发的热重载报TypeError

### ISSUE THREAD

**Issue by KotoriK** [modern-js-dev/modern.js#2074]
### 版本信息

```sh
@modern-js/app-tools@1.21.1
```

### 问题详情

```output.polyfill```设置为```ua```时，由```modern.config.js```触发的热重载会报TypeError。
## 错误堆栈
```
TypeError: flags.join is not a function
  at \home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin-polyfill@1.21.1\node_modules\@modern-js\plugin-polyfill\dist\js\node\index.js:36:31
    at Array.map (<anonymous>)
    at beforeProdServer (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin-polyfill@1.21.1\node_modules\@modern-js\plugin-polyfill\dist\js\node\index.js:32:48)
    at Array.<anonymous> (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\workflow\parallel.js:45:72)
    at \home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\farrow-pipeline\pipeline.js:58:32
    at dispatch (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\farrow-pipeline\counter.js:16:12)
    at Object.start (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\farrow-pipeline\counter.js:19:26)
    at Object.run (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\farrow-pipeline\pipeline.js:72:55)
    at Object.run (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\workflow\parallel.js:30:51)
    at runner.<computed> [as beforeProdServer] (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+plugin@1.21.1\node_modules\@modern-js\plugin\dist\js\node\manager\sync.js:157:57)
    at ModernDevServer.setupBeforeProdMiddleware (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+prod-server@1.21.1\node_modules\@modern-js\prod-server\dist\js\node\server\modern-server.js:343:40)
    at ModernDevServer.onInit (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+prod-server@1.21.1\node_modules\@modern-js\prod-server\dist\js\node\server\modern-server.js:176:16)
    at async ModernDevServer.onInit (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+server@1.21.1\node_modules\@modern-js\server\dist\js\node\server\dev-server.js:123:5)
    at async DevServer.init (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+prod-server@1.21.1\node_modules\@modern-js\prod-server\dist\js\node\server\index.js:87:5)
    at async createServer (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+app-tools@1.21.1_typescript@4.8.4\node_modules\@modern-js\app-tools\dist\js\node\utils\createServer.js:31:15)
    at async dev (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+app-tools@1.21.1_typescript@4.8.4\node_modules\@modern-js\app-tools\dist\js\node\commands\dev.js:88:15)
    at async Command.<anonymous> (\home\project\node_modules\.pnpm\registry.npmmirror.com+@modern-js+app-tools@1.21.1_typescript@4.8.4\node_modules\@modern-js\app-tools\dist\js\node\index.js:64:11)
```
## modern.config.ts
```ts
import { defineConfig } from '@modern-js/app-tools';
import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';
import { DefinePlugin } from 'webpack';

// https://modernjs.dev/docs/apis/config/overview

export default defineConfig({
  runtime: {
    router: true,
    state: false,
  },
  output: {
    disableNodePolyfill: true,
    disableSourceMap: process.env.FINAL_PRODUCT === '1',
    polyfill: 'ua',
  },
  tools: {
    terser: {
      terserOptions: {
        ecma: 2016,
        compress: { passes: 2, keep_infinity: true },
      },
    },
    babel: (config, { addPlugins }) => {
      addPlugins(['@babel/plugin-proposal-class-properties']);
      config.assumptions = {
        enumerableModuleMeta: true,
        setPublicClassFields: true,
        noDocumentAll: true,
        privateFieldsAsProperties: true,
      };
    },
    webpack: {
      plugins: [
        new VanillaExtractPlugin(),

      ],
    },
    devServer: {
      proxy: {
        '/api': {
          changeOrigin: true,
        },
      },
    },
  },
});
```
## 调试控制台打印结果
```
> flags
Set(1) {size: 1, gated}
> features
{es6: {…}}
> features.es6
{flags: Set(1)}
```

### 复现链接

应该不必

### 复现步骤

1. ```output.polyfill```设置为```ua```
2. 修改```modern.config.js```触发热重载
3. 控制台报上述错误。

**Comment by chenjiahan** [comment]
确实有这个问题，下个版本会修复哈
