### ISSUE TITLE
electron 启动报错

### ISSUE THREAD

**Issue by muwoo** [modern-js-dev/modern.js#255]
```shell 
$ pnpm run dev:electron
 WARN  Unsupported engine: wanted: {"node":">=14.17.6"} (current: {"node":"v14.15.2","pnpm":"6.19.1"})

> middle-platform-electron@0.1.0 dev:electron /Users/muwoo/mywork/middle-platform-electron
> modern dev electron


(node:47840) UnhandledPromiseRejectionWarning: TypeError: Get Error while loading config file: /Users/muwoo/mywork/middle-platform-electron/modern.config.js, please check it and retry.
(0 , _crypto.randomUUID) is not a function
    at defaultGetOutputFile (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_node-bundle-require@1.0.1@@modern-js/node-bundle-require/dist/js/node/index.js:42:127)
    at bundleRequire (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_node-bundle-require@1.0.1@@modern-js/node-bundle-require/dist/js/node/index.js:52:19)
    at bundleRequireWithCatch (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_load-config@1.0.0@@modern-js/load-config/dist/js/node/index.js:68:60)
    at loadConfig (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_load-config@1.0.0@@modern-js/load-config/dist/js/node/index.js:94:23)
    at loadUserConfig (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_core@1.0.0@@modern-js/core/dist/js/node/config/index.js:53:51)
    at init (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_core@1.0.0@@modern-js/core/dist/js/node/index.js:157:53)
    at async Object.run (/Users/muwoo/mywork/middle-platform-electron/node_modules/_@modern-js_core@1.0.0@@modern-js/core/dist/js/node/index.js:208:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:47840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by await-ovo** [comment]
提供下当前的环境呀
例如:
OS: Ubuntu 20.04.3
Node Version: 16.13.0; 
NPM Version: 8.1.2

**Comment by leeight** [comment]
@await-ovo 还是提供一个 `npx @modernjs/doctor` 把想要的信息都 dump 出来比较好。

**Comment by spcBackToLife** [comment]
@muwoo 应该。 node 版本问题， > 14.17 试试
