### ISSUE TITLE
执行 pnpm add react-ladda ladda 报错

### ISSUE THREAD

**Issue by theseusyang** [modern-js-dev/modern.js#282]
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67501:22)
    at Source.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67357:20)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Source.onclose (internal/streams/end-of-stream.js:105:38)
    at Source.emit (events.js:315:20)
    at Extract.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67501:22)
    at Source.destroy (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:67357:20)
    at Object.destroyer (internal/streams/destroy.js:166:59)
    at internal/streams/pipeline.js:58:19
    at internal/util.js:392:14
    at Source.<anonymous> (internal/streams/pipeline.js:84:7)
    at Source.<anonymous> (internal/util.js:392:14)
    at Source.onend (internal/streams/end-of-stream.js:95:49)

**Comment by targeral** [comment]
Please provide information about the environment in which you are running
